#!/bin/bash
set -euo pipefail

RELEASE_ID=137136562

list_existing() {
	curl --verbose --fail -L \
		-H "Accept: application/vnd.github+json" \
		-H "Authorization: Bearer ${GITHUB_TOKEN}" \
		-H "X-GitHub-Api-Version: 2022-11-28" \
		"https://api.github.com/repos/hikeratlas/qrank/releases/${RELEASE_ID}/assets" |
		jq .[].id
}

delete_existing() {
	while read -r asset_id; do
		echo "deleting ${asset_id}"
		curl --verbose --fail -L \
			-X DELETE \
			-H "Accept: application/vnd.github+json" \
			-H "Authorization: Bearer ${GITHUB_TOKEN}" \
			-H "X-GitHub-Api-Version: 2022-11-28" \
			"https://api.github.com/repos/hikeratlas/qrank/releases/assets/${asset_id}"
	done < <(list_existing)
}

publish() {
	curl --verbose --fail -L \
		-X POST \
		-H "Accept: application/vnd.github+json" \
		-H "Authorization: Bearer ${GITHUB_TOKEN}" \
		-H "X-GitHub-Api-Version: 2022-11-28" \
		-H "Content-Type: application/octet-stream" \
		"https://uploads.github.com/repos/hikeratlas/qrank/releases/${RELEASE_ID}/assets?name=qrank.db" \
		--data-binary "@README.md"
}

delete_existing
publish
